import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "relative h-full geistSans antialiased",
          geistSans.variable
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <div className="flex-1 flex-grow">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
